version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=quitance
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./data/db:/var/lib/postgresql/data

  oradb:
    image: gvenzl/oracle-xe
    environment:
      - ORACLE_PASSWORD=oracle
      - APP_USER=quittance
      - APP_USER_PASSWORD=123Gadjan789
    ports:
      - 1521:1521
      - 5500:5500
    volumes: 
      - ./data/oradb:/opt/oracle/oradata

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./static:/code/static
      - ./media:/code/media
      - .env:/code/.env
      - ./.gitignore:/code/.gitignore
      - ./requirements.txt:/code/requirements.txt
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - oradb
