# Generated by Django 2.2 on 2020-11-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('year', models.IntegerField(null=True)),
                ('best_of_compilation', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'album',
            },
        ),
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_definition', models.TextField()),
                ('report_type', models.CharField(max_length=30)),
                ('remark', models.TextField(null=True)),
                ('last_modified_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'report_definition',
            },
        ),
        migrations.CreateModel(
            name='ReportRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=36)),
                ('report_definition', models.TextField()),
                ('data', models.TextField()),
                ('is_test_data', models.BooleanField()),
                ('pdf_file', models.BinaryField(null=True)),
                ('pdf_file_size', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'report_request',
            },
        ),
    ]
