# Generated by Django 2.2 on 2020-11-20 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myreportbro', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
    ]
