# Generated by Django 2.2 on 2020-11-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreportbro', '0002_delete_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('year', models.IntegerField(null=True)),
                ('best_of_compilation', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'album',
            },
        ),
    ]
