# Generated by Django 3.2.8 on 2022-07-16 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quitance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bordereau',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quitance.agent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bordereau',
            name='date_reception',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date reception du bordereau'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bordereaudetail',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quitance.agent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compte',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quitance.agent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sousstructure',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quitance.agent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structure',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quitance.agent'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Journee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100, unique=True, verbose_name='Journee comptable')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('actived', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Structure',
                'verbose_name_plural': 'Structures',
            },
        ),
        migrations.AddField(
            model_name='bordereau',
            name='journee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quitance.journee'),
            preserve_default=False,
        ),
    ]
