# Generated by Django 3.2.8 on 2022-07-16 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quitance', '0002_auto_20220716_2229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'permissions': (('versement_numeraire', 'Peut effectuer un versement numeraire'), ('depot_cheque', 'Peut effectuer un dépôt chèque')), 'verbose_name': 'Agent', 'verbose_name_plural': 'Agents'},
        ),
    ]
