# Generated by Django 3.2.8 on 2022-07-17 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quitance', '0003_alter_agent_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bordereau',
            name='date_reception',
            field=models.DateField(verbose_name='Date reception'),
        ),
        migrations.AlterField(
            model_name='bordereau',
            name='poste_comptable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quitance.sousstructure'),
        ),
        migrations.AlterField(
            model_name='bordereaudetail',
            name='bordereau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quitance.bordereau'),
        ),
    ]
