# Generated by Django 3.2.8 on 2022-07-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quitance', '0005_auto_20220718_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partiversante',
            name='mail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mail'),
        ),
        migrations.AlterField(
            model_name='partiversante',
            name='telephone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Téléphone'),
        ),
    ]
