# Generated by Django 3.2.8 on 2022-07-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quitance', '0008_alter_agent_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bordereau',
            name='nom_prenom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom et Prénom'),
        ),
        migrations.AlterField(
            model_name='journee',
            name='date',
            field=models.DateField(max_length=100, verbose_name='Journee comptable'),
        ),
        migrations.AlterUniqueTogether(
            name='journee',
            unique_together={('date', 'created_by')},
        ),
        migrations.RemoveField(
            model_name='journee',
            name='code',
        ),
    ]
