# Generated by Django 3.2.8 on 2022-07-20 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quitance', '0010_auto_20220719_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bordereau',
            name='compte',
        ),
        migrations.AddField(
            model_name='bordereaudetail',
            name='compte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quitance.compte'),
            preserve_default=False,
        ),
    ]
