# Generated by Django 3.2.8 on 2022-07-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quitance', '0012_auto_20220720_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='bordereaudetail',
            name='titulaire',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Partie Versante'),
        ),
        migrations.AlterField(
            model_name='bordereau',
            name='type_operation',
            field=models.IntegerField(choices=[(1, 'VERSEMENT NUMERAIRE'), (2, 'DEPOT CHEQUE')], verbose_name='Type Operation'),
        ),
    ]
