# Generated by Django 3.2.8 on 2022-07-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quitance', '0015_auto_20220721_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quitance',
            name='numero',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Numero Quittance'),
        ),
        migrations.AlterField(
            model_name='quitance',
            name='numero_dr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero Declaration recette'),
        ),
    ]
