# Generated by Django 3.2.8 on 2022-08-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quitance', '0018_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='code',
            field=models.SlugField(default='', max_length=20, verbose_name='code'),
            preserve_default=False,
        ),
    ]
